### ISSUE TITLE
Any installation instructions ?

### ISSUE THREAD

**Issue by atv2016** [ibielopolskyi/smartthings_fridge_camera#1]

**Comment by Krzysztonek** [comment]
https://github.com/home-assistant/core/issues/28473#issuecomment-1891940157

**Comment by ReenigneArcher** [comment]
It's available in HACS. Just search for `samsung`

**Comment by atv2016** [comment]
You mean after adding this custom component ?
________________________________

**Comment by ReenigneArcher** [comment]
HACS can install the custom component for you

**Comment by atv2016** [comment]
Hmm, I have nothing in the HACS library that mentions samsung other then SamsungTV and SamsungTV Tizen ?
________________________________

**Comment by ReenigneArcher** [comment]
![image](https://github.com/ibielopolskyi/smartthings_fridge_camera/assets/42013603/0ddc697c-d0e8-4035-90ef-fbf44076f0ed)

**Comment by atv2016** [comment]
Duh I hadn't added it yet to the HACS repo. My bad. Thanks I will go and have a look now.

**Comment by NickWhitNTES** [comment]
Hi.  Sorry to be a dumbass, but how do we install this?

I have HACS but am at a loss on what to do here.  Also, does this intergration sit alongside the normal SmartThings one?

**Comment by ibielopolskyi** [comment]
> but how do we install this?

This should be what you are looking for: https://hacs.xyz/docs/faq/custom_repositories/

> Also, does this intergration sit alongside the normal SmartThings one?

Yes, it's completely unrelated. I'm using both myself.
